@startuml airportDesign
!theme sketchy-outline

class Restaurant {
	index : Integer
	name : String
	menus : Array

	addMenu()
	removeMenu()
}

class Menu {
	index : Integer
	name : String
	items : Array

	addItem()
	removeItem()
}

class Items {
	index : Integer
	name : String
	price : Real
	inStock : Boolean

	changePrice()
	toggleStock()
}

Restaurant --{ Menu
Menu --{ Items

@enduml